# Generated by Django 5.0.6 on 2024-06-11 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_teacher_city_teacher_country_teacher_state'),
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.student'),
        ),
    ]
