# Generated by Django 5.0.4 on 2024-05-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_excelupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelupload',
            old_name='DOB',
            new_name='dob',
        ),
    ]
