# Generated by Django 5.0.4 on 2024-06-03 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_teacher_email'),
        ('communicationapp', '0002_remove_announcement_batch_remove_announcement_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=500)),
                ('document', models.FileField(blank=True, null=True, upload_to='notifications/')),
                ('posted_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='adminapp.teacher')),
            ],
        ),
    ]
