# Generated by Django 5.0.4 on 2024-06-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicationapp', '0003_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
