# Generated by Django 5.0.4 on 2024-05-28 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('reportcard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='certificateapp.reportcard')),
                ('total_marks', models.IntegerField()),
                ('performance', models.CharField(max_length=10)),
            ],
            bases=('certificateapp.reportcard',),
        ),
    ]
