# Generated by Django 5.0.4 on 2024-05-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificateapp', '0002_achievements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievements',
        ),
    ]
