# Generated by Django 5.0.4 on 2024-05-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='break_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='break_start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
