# Generated by Django 5.0.4 on 2024-06-04 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_teacher_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='City1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.city1'),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.country1'),
        ),
        migrations.CreateModel(
            name='State1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.country1')),
            ],
        ),
        migrations.AddField(
            model_name='city1',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.state1'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.state1'),
        ),
    ]
