# Generated by Django 5.0.4 on 2024-06-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_city1_country1_student_city_student_country_state1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.city1'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.country1'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.state1'),
        ),
    ]
