# Generated by Django 5.0.6 on 2024-06-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_teacher_city_teacher_country_teacher_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['name'], name='adminapp_te_name_454df6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['username'], name='adminapp_te_usernam_fdfc68_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['email'], name='adminapp_te_email_efe1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['phone_number'], name='adminapp_te_phone_n_95b667_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['course'], name='adminapp_te_course__021813_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['batch'], name='adminapp_te_batch_i_1e0f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['country'], name='adminapp_te_country_3ba787_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['state'], name='adminapp_te_state_i_880fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['city'], name='adminapp_te_city_id_651fbd_idx'),
        ),
    ]
