# Generated by Django 5.0.6 on 2024-06-19 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_teacher_email_alter_teacher_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='username',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='adminmodel',
            index=models.Index(fields=['username'], name='adminapp_ad_usernam_659248_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='adminapp_co_name_1c2b78_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['phone_number'], name='adminapp_st_phone_n_7ebccc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['date_of_birth'], name='adminapp_st_date_of_b6a1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['gender'], name='adminapp_st_gender_8e4b77_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['courses'], name='adminapp_st_courses_206f84_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['batch'], name='adminapp_st_batch_i_c5a37c_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['country'], name='adminapp_st_country_cc17de_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['state'], name='adminapp_st_state_i_30a398_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['city'], name='adminapp_st_city_id_668dc7_idx'),
        ),
    ]
